# Generated by Django 4.2.9 on 2024-03-26 01:57

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BangChuyenBien',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChuyenBienSo', models.IntegerField(default=0, help_text='Số thứ tự chuyến biển trong năm')),
                ('NgayXuatBen', models.DateField(default=datetime.date(1900, 1, 1), help_text='Ngày xuất bến', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2024, 3, 26))])),
                ('ViDoXuatBen', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('KinhDoXuatBen', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('NgayVeBen', models.DateField(default=datetime.date(1900, 1, 1), help_text='Ngày về bến', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2024, 3, 26))])),
                ('ViDoVeBen', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('KinhDoVeBen', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('KhoiLuongChuyenTai', models.IntegerField(blank=True, help_text='Khối lượng chuyến tải', null=True)),
                ('KhoiLuongDanhBat', models.IntegerField(default=0)),
                ('CangVeBen', models.ForeignKey(default=1, help_text='Mã cảng về bến', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cangveben', to='core.bangcangca')),
                ('CangXuatBen', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cangxuatben', to='core.bangcangca')),
            ],
            options={
                'verbose_name_plural': 'Bảng chuyến biển',
            },
        ),
        migrations.RenameField(
            model_name='bangloaicadanhbat',
            old_name='MaLoaiCa',
            new_name='IDCa',
        ),
        migrations.RenameField(
            model_name='bangloaicadanhbat',
            old_name='TenLoaiCa',
            new_name='Ten',
        ),
        migrations.RemoveField(
            model_name='bangloaicadanhbat',
            name='IDLoaiCa',
        ),
        migrations.AddField(
            model_name='bangloaicadanhbat',
            name='ID',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bangchutau',
            name='NgaySinh',
            field=models.DateField(default=datetime.date(1900, 1, 1), help_text='Ngày tháng năm sinh chủ tàu', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2024, 3, 26))]),
        ),
        migrations.AlterField(
            model_name='bangtau',
            name='NgayDangKy',
            field=models.DateField(default=datetime.date(1900, 1, 1), help_text='Ngày đăng ký', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2024, 3, 26))]),
        ),
        migrations.AlterField(
            model_name='bangtau',
            name='NgaySanXuat',
            field=models.DateField(blank=True, help_text='Ngày sản xuất', null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2024, 3, 26))]),
        ),
        migrations.AlterField(
            model_name='bangthietbinhatkykhaithac',
            name='NgaySanXuat',
            field=models.DateField(blank=True, help_text='Ngày sản xuất', null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2024, 3, 26))]),
        ),
        migrations.AlterField(
            model_name='bangthuyentruong',
            name='NgaySinh',
            field=models.DateField(default=datetime.date(1900, 1, 1), help_text='Ngày tháng năm sinh thuyền trưởng', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2024, 3, 26))]),
        ),
        migrations.CreateModel(
            name='BangNhatKy',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaNhatKy', models.CharField(blank=True, max_length=24, null=True)),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('IDChuyenBien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.bangchuyenbien')),
                ('IDThietBi', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.bangtau')),
            ],
            options={
                'verbose_name_plural': 'Bảng nhật ký',
            },
        ),
        migrations.CreateModel(
            name='BangMeLuoi',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MeLuoiSo', models.IntegerField(default=0, help_text='Số thứ tự của mẻ lưới của chuyến biển')),
                ('ThoiDiemThaNguCu', models.DateTimeField()),
                ('ViDoThaNguCu', models.DecimalField(decimal_places=6, default=0, help_text='Vĩ độ thả ngư cụ', max_digits=12)),
                ('KinhDoThaNguCu', models.DecimalField(decimal_places=6, default=0, help_text='Kinh độ thả ngư cụ', max_digits=12)),
                ('ThoiDiemThuNguCu', models.DateTimeField()),
                ('ViDoThuNguCu', models.DecimalField(decimal_places=6, default=0, help_text='Vĩ độ thu ngư cụ', max_digits=12)),
                ('KinhDoThuNguCu', models.DecimalField(decimal_places=6, default=0, help_text='Kinh độ thu ngư cụ', max_digits=12)),
                ('TongSanLuong', models.IntegerField(default=0, help_text='Tổng sản lượng của mẻ lưới')),
                ('IDChuyenBien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.bangchuyenbien')),
            ],
            options={
                'verbose_name_plural': 'Bảng mẻ lưới',
            },
        ),
        migrations.CreateModel(
            name='BangLoaiCaDuocDanhBatTrongMeLuoi',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SanLuong', models.IntegerField(default=0, help_text='Sản lượng loại cá được đánh bắt trong mẻ lưới')),
                ('IDLoaiCa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.bangloaicadanhbat')),
                ('IDMeLuoi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.bangmeluoi')),
            ],
            options={
                'verbose_name_plural': 'Bảng loại cá đánh bắt được trong mẻ lưới',
            },
        ),
        migrations.AddField(
            model_name='bangchuyenbien',
            name='IDTau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.bangtau'),
        ),
        migrations.AddField(
            model_name='bangchuyenbien',
            name='VungBienDanhBat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.bangvungbiendanhbat'),
        ),
    ]
