# Generated by Django 4.2.9 on 2024-03-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangvitritau',
            name='Ngay',
            field=models.DateTimeField(),
        ),
    ]
